import 'package:flutter/material.dart';

class Job {
  final String id = UniqueKey().toString();
  final String title;
  final String company;
  final String schedule;
  final String location;
  final String? imagePath;
  bool isFavorite;
  double? salary;
  String? description;
  List<String>? requirements;
  List<String>? benefits;
  List<String>? skills;

  Job({
    required this.title,
    required this.company,
    required this.schedule,
    required this.location,
    required this.imagePath,
    this.isFavorite = false,
    this.salary,
    this.description,
    this.requirements,
    this.benefits,
    this.skills,
  });
}

List<Job> jobs = [
  Job(
    title: 'Backend Developer',
    company: 'Amazon Web Services',
    schedule: 'Full-time',
    location: 'New York, NY',
    imagePath: 'assets/images/amazon.png',
    isFavorite: true,
    salary: 120000,
    description: 'We are looking for a Backend Developer to join our team. You will be responsible for building and maintaining server-side applications.',
    requirements: ['Experience with Node.js', 'Knowledge of REST APIs'],
    benefits: ['Health insurance', '401(k) plan'],
    skills: ['JavaScript', 'Node.js', 'Express.js'],
  ),
  Job(
    title: 'Data Scientist',
    company: 'Google',
    schedule: 'Part-time',
    location: 'California, CA',
    imagePath: 'assets/images/google.png',
    isFavorite: false,
    salary: 150000,
    description: 'Join our team as a Data Scientist to analyze large datasets and provide insights that drive business decisions.',
    requirements: ['Proficiency in Python', 'Experience with machine learning'],
    benefits: ['Flexible working hours', 'Remote work options'],
    skills: ['Python', 'Machine Learning', 'Data Analysis'],
  ),
  Job(
    title: 'Product Manager',
    company: 'Meta',
    schedule: 'Contract',
    location: 'Menlo Park, CA',
    imagePath: 'assets/images/meta.png',
    isFavorite: false,
    salary: 140000,
    description: 'We are seeking a Product Manager to lead our product development efforts.',
    requirements: ['Experience with Agile methodologies', 'Strong communication skills'],
    benefits: ['Stock options', 'Health and wellness programs'],
    skills: ['Product Management', 'Agile', 'Scrum'],
  ),
  Job(
    title: 'UI/UX Designer',
    company: 'Apple',
    schedule: 'Full-time',
    location: 'Cupertino, CA',
    imagePath: 'assets/images/apple.png',
    isFavorite: false,
    salary: 130000,
    description: 'We are looking for a UI/UX Designer to create user-friendly interfaces.',
    requirements: ['Experience with design tools', 'Strong portfolio'],
    benefits: ['Health insurance', 'Paid time off'],
    skills: ['Figma', 'Adobe XD', 'User Research'],
  ),
  Job(
    title: 'DevOps Engineer',
    company: 'Microsoft',
    schedule: 'Full-time',
    location: 'Redmond, WA',
    imagePath: 'assets/images/microsoft.png',
    isFavorite: false,
    salary: 140000,
    description: 'We are looking for a DevOps Engineer to streamline our development and operations processes.',
    requirements: ['Experience with CI/CD tools', 'Knowledge of cloud platforms'],
    benefits: ['Health insurance', '401(k) plan'],
    skills: ['Docker', 'Kubernetes', 'AWS'],
  ),
  Job(
    title: 'Prompt Engineer',
    company: 'OpenAI',
    schedule: 'Full-time',
    location: 'San Francisco, CA',
    imagePath: 'assets/images/chatgpt.png',
    isFavorite: false,
    salary: 150000,
    description: 'We are looking for a Prompt Engineer to design and implement effective prompts for our AI models.',
    requirements: ['Experience with natural language processing', 'Strong programming skills'],
    benefits: ['Flexible working hours', 'Remote work options'],
    skills: ['Python', 'NLP', 'Machine Learning'],
  ),
  Job(
    title: 'Telegram Bot Developer',
    company: 'Telegram',
    schedule: 'Full-time',
    location: 'Remote',
    imagePath: 'assets/images/telegram.png',
    isFavorite: false,
    salary: 120000,
    description: 'Join our team as a Telegram Bot Developer to create innovative bots for our platform.',
    requirements: ['Experience with Telegram Bot API', 'Strong programming skills'],
    benefits: ['Health insurance', 'Paid time off'],
    skills: ['Python', 'Node.js', 'Telegram Bot API'],
  ),

  Job(
    title: 'JavaScript Developer',
    company: 'X Corp',
    schedule: 'Full-time',
    location: 'San Francisco, CA',
    imagePath: 'assets/images/twitter.png',
    isFavorite: false,
    salary: 110000,
    description: 'We are looking for a JavaScript Developer to join our team and work on exciting projects.',
    requirements: ['Experience with React', 'Knowledge of REST APIs'],
    benefits: ['Health insurance', '401(k) plan'],
    skills: ['JavaScript', 'React', 'Node.js'],
  ),
  Job(
    title: 'Content Creator',
    company: 'TikTok',
    schedule: 'Part-time',
    location: 'Remote',
    imagePath: 'assets/images/tik-tok.png',
    isFavorite: false,
    salary: 80000,
    description: 'Join our team as a Content Creator to produce engaging content for our platform.',
    requirements: ['Experience with video editing', 'Strong creative skills'],
    benefits: ['Flexible working hours', 'Remote work options'],
    skills: ['Video Editing', 'Content Creation', 'Social Media'],
  ),
  Job(
    title: 'Software Engineer Intern',
    company: 'Facebook',
    schedule: 'Full-time',
    location: 'Menlo Park, CA',
    imagePath: 'assets/images/facebook.png',
    isFavorite: false,
    salary: 70000,
    description: 'We are looking for a Software Engineer Intern to assist with various projects.',
    requirements: ['Familiarity with programming languages', 'Strong problem-solving skills'],
    benefits: ['Mentorship opportunities', 'Networking events'],
    skills: ['JavaScript', 'Python', 'Git'],
  ),
  Job(
    title: 'Frontend Developer',
    company: 'Instagram',
    schedule: 'Full-time',
    location: 'Menlo Park, CA',
    imagePath: 'assets/images/instagram.png',
    isFavorite: false,
    salary: 120000,
    description: 'We are looking for a Frontend Developer to create engaging user interfaces.',
    requirements: ['Experience with React', 'Strong design skills'],
    benefits: ['Health insurance', '401(k) plan'],
    skills: ['JavaScript', 'React', 'CSS'],
  ),
  Job(
    title: 'Infrastructure Engineer',
    company: 'Nvidia',
    schedule: 'Full-time',
    location: 'Santa Clara, CA',
    imagePath: 'assets/images/nvidia.png',
    isFavorite: false,
    salary: 140000,
    description: 'We are looking for an Infrastructure Engineer to manage our cloud infrastructure.',
    requirements: ['Experience with cloud platforms', 'Strong networking skills'],
    benefits: ['Health insurance', '401(k) plan'],
    skills: ['AWS', 'Azure', 'Networking'],
  ),
  Job(
    title: 'Mobile App Developer',
    company: 'Tesla',
    schedule: 'Full-time',
    location: 'Palo Alto, CA',
    imagePath: 'assets/images/tesla.png',
    isFavorite: false,
    salary: 130000,
    description: 'We are looking for a Mobile App Developer to create innovative applications for our platform.',
    requirements: ['Experience with Flutter', 'Strong programming skills'],
    benefits: ['Health insurance', 'Paid time off'],
    skills: ['Flutter', 'Dart', 'Mobile Development'],
  ),
  Job(
    title: 'Backend Developer',
    company: 'WhatsApp',
    schedule: 'Full-time',
    location: 'Menlo Park, CA',
    imagePath: 'assets/images/whatsapp.png',
    isFavorite: false,
    salary: 120000,
    description: 'We are looking for a Backend Developer to build and maintain our server-side applications.',
    requirements: ['Experience with Node.js', 'Knowledge of databases'],
    benefits: ['Health insurance', '401(k) plan'],
    skills: ['Node.js', 'Express', 'MongoDB'],
  ),
  Job(
    title: 'Infrastructure Engineer',
    company: 'Netflix',
    schedule: 'Full-time',
    location: 'Los Gatos, CA',
    imagePath: 'assets/images/netflix.png',
    isFavorite: false,
    salary: 140000,
    description: 'We are looking for an Infrastructure Engineer to manage our cloud infrastructure.',
    requirements: ['Experience with cloud platforms', 'Strong networking skills'],
    benefits: ['Health insurance', '401(k) plan'],
    skills: ['AWS', 'Azure', 'Networking'],
  ),
  Job(
    title: 'iOS Developer',
    company: 'Apple',
    schedule: 'Full-time',
    location: 'Cupertino, CA',
    imagePath: 'assets/images/apple.png',
    isFavorite: false,
    salary: 130000,
    description: 'We are looking for an iOS Developer to create innovative applications for our platform.',
    requirements: ['Experience with Swift', 'Strong programming skills'],
    benefits: ['Health insurance', 'Paid time off'],
    skills: ['Swift', 'Xcode', 'iOS Development'],
  ),
  Job(
    title: 'Android Developer',
    company: 'Google',
    schedule: 'Full-time',
    location: 'Mountain View, CA',
    imagePath: 'assets/images/google.png',
    isFavorite: false,
    salary: 130000,
    description: 'We are looking for an Android Developer to create innovative applications for our platform.',
    requirements: ['Experience with Kotlin', 'Strong programming skills'],
    benefits: ['Health insurance', 'Paid time off'],
    skills: ['Kotlin', 'Android Studio', 'Mobile Development'],
  ),
  Job(
    title: 'Cloud Engineer',
    company: 'Amazon',
    schedule: 'Full-time',
    location: 'Seattle, WA',
    imagePath: 'assets/images/amazon.png',
    isFavorite: false,
    salary: 140000,
    description: 'We are looking for a Cloud Engineer to design and implement cloud solutions.',
    requirements: ['Experience with AWS', 'Strong scripting skills'],
    benefits: ['Health insurance', '401(k) plan'],
    skills: ['AWS', 'Terraform', 'CloudFormation'],
  ),
  Job(
    title: 'AI Research Scientist',
    company: 'OpenAI',
    schedule: 'Full-time',
    location: 'San Francisco, CA',
    imagePath: 'assets/images/chatgpt.png',
    isFavorite: false,
    salary: 150000,
    description: 'We are looking for an AI Research Scientist to join our team and work on cutting-edge AI projects.',
    requirements: ['PhD in Computer Science or related field', 'Experience with machine learning frameworks'],
    benefits: ['Health insurance', '401(k) plan'],
    skills: ['Python', 'TensorFlow', 'Machine Learning'],
  ),
  Job(
    title: 'Flutter Developer',
    company: 'Google',
    schedule: 'Full-time',
    location: 'Mountain View, CA',
    imagePath: 'assets/images/google.png',
    isFavorite: false,
    salary: 130000,
    description: 'We are looking for a Flutter Developer to create beautiful and performant mobile applications.',
    requirements: ['Experience with Flutter', 'Strong programming skills'],
    benefits: ['Health insurance', 'Paid time off'],
    skills: ['Flutter', 'Dart', 'Mobile Development'],
  ),
];